[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.60"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
